### PR TITLE
Invocation exception now thrown if cannot invoke callable

### LINKED ISSUE #6: Invocation exception thrown wrong
Currently, when a problem happens **inside** the callback given to `_invokeCallable()`, and invocation exception is thrown that wraps it. This is a job for `InternalExceptionInterface`; `InvocationExceptionInterface` should be thrown when there is a problem **invoking** the callable, not inside it.

### PR DESCRIPTION
**Pull request by XedinUnknown**
Aims to fix #6.

### CODE REVIEW

File: src/CreateReflectionForCallableCapableTrait.php [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+     *
+     * @since [*next-version*]
+     *
+     * @param array|stdClass|Traversable $value The value to normalize.
+     *
+     * @throws InvalidArgumentException If value cannot be normalized.
+     *
+     * @return array The normalized value.
+     */
+    abstract protected function _normalizeArray($value);
```
Comment (mecha) [inline src/CreateReflectionForCallableCapableTrait.php]: Unused in this trait.

File: src/InvokeCallableCapableTrait.php [hunk 2]
```diff
@@ -26,7 +32,8 @@
      *
      * @throws InvalidArgumentException     If the callable is not callable.
      * @throws InvalidArgumentException     if the args are not a valid list.
```
Comment (mecha) [inline src/InvokeCallableCapableTrait.php]: Capitalization inconsistency.

File: src/InvokeCallableCapableTrait.php [hunk 3]
```diff
@@ -39,51 +46,71 @@ protected function _invokeCallable($callable, $args)
...
+            if ($reflection instanceof ReflectionMethod) {
+                $target = is_object($callable[0])
+                    ? $callable[0]
+                    : null;
+
+                return $reflection->invokeArgs($target, $args);
+            } else {
+                return $reflection->invokeArgs($args);
+            }
+        } catch (RootException $e) {
```
Comment (mecha) [inline src/InvokeCallableCapableTrait.php:67]: The contents of this `try..catch` block almost look like functionality that ought to exist in a separate trait; one that invokes a reflection regardless of whether or not it's a `ReflectionFunction` or `ReflectionMethod`.

What do you think? Perhaps a future improvement, if nothing else.

File: src/NormalizeMethodCallableCapableTrait.php [hunk 4]
```diff
@@ -0,0 +1,136 @@
...
+        } catch (InvalidArgumentException $e) {
+            // Just continue
+        }
+
+        // Normalizing to array
+        $callable = $this->_normalizeArray($callable);
+        $callable = array_slice($callable, 0, $amtPartsRequired);
+
+        // Array must have exactly 2 parts
+        if (count($callable) !== $amtPartsRequired) {
```
Comment (mecha) [inline src/NormalizeMethodCallableCapableTrait.php:56]: Not really a bug or an issue, more of a suggestion.

Given that `$callable` is being sliced up to a maximum of `$amtPartsRequired`, there is _no_ possible way for `$callable` to have more than 2 elements. Consider changing the expression operator to `<` for code clarity and consistency with the exception message that may be thrown (_"... must have at least ..."_).

**Review by mecha — CHANGES_REQUESTED** [review]
I couldn't leave a review comment for this, because it's not a part of the changeset of this PR. The description at [`InvokeCallbackCapableTrait.php#14`](https://github.com/Dhii/callback-abstract/blob/task/6_invocation-exception-thrown-wrong/src/InvokeCallbackCapableTrait.php#L14) needs some elaboration.

Consider _"Functionality for something that has a callback and can invoke it."_.

File: src/InvokeCallableCapableTrait.php (hunk 3 above)
Comment (XedinUnknown) [reply src/InvokeCallableCapableTrait.php:67]: I don't know if this is possible. They are different APIs.

Comment (mecha) [reply src/InvokeCallableCapableTrait.php:67]: True. But we can document `@param ReflectionFunction|ReflectionMethod`, no?

Comment (XedinUnknown) [reply src/InvokeCallableCapableTrait.php:67]: True. But what do you invoke it with?

Comment (mecha) [reply src/InvokeCallableCapableTrait.php:67]: Yeah ... ok, disregard for now.

File: src/NormalizeMethodCallableCapableTrait.php (hunk 4 above)
Comment (XedinUnknown) [reply src/NormalizeMethodCallableCapableTrait.php:56]: Valid point. But from another perspective, exactly 2 elements is precisely what is required, and this is what I'm checking for. To avoid delays, I would prefer to leave this as is.

**Review by mecha — APPROVED** [review]
**Top notch** 👌

**Comment by XedinUnknown** [comment]
Why can't I <3 request or approve comments?? :(
